
-- create
CREATE TABLE IF NOT EXISTS EMPLOYEE(
    ID INT PRIMARY KEY,
    SALARY INT NOT NULL
);

INSERT INTO EMPLOYEE (ID, SALARY) VALUES(1, 100);
INSERT INTO EMPLOYEE (ID, SALARY) VALUES(2, 200);
INSERT INTO EMPLOYEE (ID, SALARY) VALUES(3, 300);

SELECT * FROM EMPLOYEE;

Select MAX(SALARY) AS MAXIMUM_SALARY FROM EMPLOYEE;
SELECT avg(SALARY) AS avg_salary FROM EMPLOYEE;
SELECT salary FROM Employee
ORDER BY salary DESC
LIMIT 1 OFFSET 1;
